#!/bin/bash

get () {
  percent=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
  echo "$percent"
}

set_vol () {
  local vol=$1
  local sink=$(pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1)
  pactl set-sink-volume $sink "$vol%"
}

if [[ $1 == "get" ]]; then get && exit; fi
if [[ $1 == "set" ]]; then set_vol $2 && exit; fi
