#!/bin/bash

get_icon () {
  local widgets_dir="$HOME/.config/eww/widgets"
  if [[ $(eww -c $widgets_dir state) != "" ]]; then
    echo ""
  else
    status=$(playerctl status)
    if [[ $status == "Paused" ]]; then
      echo ""
    else
      echo ""
    fi
  fi
}

toggle () {
  local widgets_dir="$HOME/.config/eww/widgets"
  if [[ $(eww -c $widgets_dir state) != "" ]]; then
    eww -c $widgets_dir close-all
  else
    eww -c $widgets_dir open music
  fi
}

if [[ $1 == "get-audio" ]]; then
  widgets_dir="$HOME/.config/eww/widgets"
  if [[ $(eww -c $widgets_dir state) != "" ]]; then
    echo "Press to close opened widget!"
  else
    playerctl metadata --format "{{ artist }}: {{ title }}" 2>&1
  fi
elif [[ $1 == "get-icon" ]]; then
  get_icon
elif [[ $1 == "toggle-widget" ]]; then
  toggle
fi
