#!/bin/bash

get_offcmd () {
  local os="$(grep -m1 "NAME=" </etc/os-release | cut -d '"' -f 2)"
  if [[ $os == 'void' || $os == "Void" ]]; then
    echo "sudo poweroff"
  else
    echo "sudo shutdown now"
  fi
}

if [[ $1 == 'reboot' ]]; then
  kitty -e sudo reboot
elif [[ $1 == 'off' ]]; then
  offcmd=$(get_offcmd)
  kitty -e $offcmd
fi
