#!/bin/bash

# autostart
bash $HOME/.config/bspwm/scripts/autostart.sh

# use 1 to use the scripts/monitor.sh file (configure it file editing it!)
MONITOR_SUPPORT=1

function setopt () {
  bspc config "$1" "$2"
}

# borders and gaps
setopt border_width 1
setopt window_gap 20

BACKGROUND=#061115

setopt normal_border_color "$BACKGROUND"
setopt focused_border_color "$BACKGROUND"
setopt presel_feedback_color "$BACKGROUND"

export PATH="$HOME/.local/bin:$PATH"

pkill borders ; borders &

# behaviour stuff
setopt left_padding 65
setopt split_ratio 0.52
setopt borderless_monocle false
setopt gapless_monocle false
setopt single_monocle false

# eww fullscreen
bspc subscribe node_state | while read -r _ _ _ _ state flag; do
  if [ "$state" != "fullscreen" ]; then
    continue
  fi
  if [ "$flag" == on ]; then
    setopt left_padding 0
    killall -q eww
  else
    setopt left_padding 65
    bash $HOME/.config/eww/bar/launch.sh
  fi
done &

# pointer
setopt focus_follows_pointer true
setopt pointer_follows_focus true
setopt pointer_follows_monitor true

# plank compatibility
bspc rule -a Plank layer=above manage=on border=off

# monitor
if [[ $MONITOR_SUPPORT == 1 ]]; then
  bash $HOME/.config/bspwm/scripts/monitor.sh
else
  bspc monitor primary -d 1 2 3 4 5 6 7 8 9 X
fi
