#!/bin/bash

if [[ $1 == "memory" ]]; then
  free -t | awk 'NR == 2 {printf("%.2f"), $3/$2*100}' | awk '{ print int($1) }'
elif [[ $1 == "processor" ]]; then
  grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}' | awk '{print int($1)}'
fi
